JOB_UUID_LENGTH = 8
M3GNET_MAX_RELAX_STEPS = 1000
M3GNET_RELAXED_POSCAR_SUBFIX = '.m3g.vasp'
AIRSS_INIT_POSCAR_SUBFIX = '.init.vasp'
STRUC_GROUPS_INFO_JSON = 'res.structure-groups-info.json'
UNDETERMINED_SPACE_GROUP = 'UNKNOWN'